# Generated by Django 3.1.8 on 2021-05-01 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='featured_image',
            field=models.ForeignKey(help_text='Select an image to be featured on the service page, it will be used as a banner', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image'),
        ),
    ]
