# Generated by Django 3.1.8 on 2021-04-30 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_button_page',
            field=models.ForeignKey(blank=True, help_text='Select a page that this button leads to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_button_text',
            field=models.CharField(default='', help_text='Enter text that will appear on the button on the banner', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_image',
            field=models.ForeignKey(help_text='Pick an image that will displayed as the banner image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_text',
            field=models.CharField(default='', help_text='Enter text that will be displayed on the banner image', max_length=200),
        ),
    ]
