# Generated by Django 3.1.8 on 2021-05-02 14:53

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentistPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(help_text='Enter name of the dentist', max_length=50)),
                ('small_description', models.TextField(help_text='Enter a small description about the dentist')),
                ('about', wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock(help_text='Enter the title of this section of the about')), ('text', wagtail.core.blocks.RichTextBlock(help_text='Enter the description of this section'))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
