# Generated by Django 3.1.8 on 2021-05-02 17:32

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentistpage',
            name='about',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock())]))]),
        ),
    ]
